# Generated by Django 4.1.7 on 2023-03-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='dweet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='likes', to='dwitter.dweet'),
        ),
    ]
